apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookingdb-pvc-claim
  namespace: cargotracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ibmc-block-silver
