apiVersion: v1
data:
  bookingdb.user.name: Ym9va2luZ21zZGIK
  bookingdb.user.password: Ym9va2luZ21zZGIK
  rabbitmq.user.name: YXBwdXNlcgo=
  rabbitmq.user.password: cGFzc3cwcmQK
kind: Secret
metadata:
  name: cargotracker-booking-credentials
type: Opaque